packages:
  - 'account-data'
  - 'hello-solana'
  - 'global-state-counter'
  - 'checking-instruction-accounts'
  - 'close-account'
  - 'create-account'
  - 'cross-program-invocations'
  - 'pda-rent-payer'